Update az.po
davidmhewitt/clipped pull request #31
Opened 2018-10-20 05:50 UTC by manymous

2018-10-21 12:14 UTC, fitojb requested changes

2018-10-21 12:14 UTC, fitojb commented on po/az.po
> +"<b> Qeyd: </ b> İndi, Clipped avtomatik olaraq arxa fonda başlayacaq"
Please remove the stray spaces in the XML tag, like this:

```suggestion
"<b>Qeyd:</b> İndi, Clipped avtomatik olaraq arxa fonda başlayacaq"
```

2018-10-21 12:14 UTC, fitojb commented on po/az.po
> +"applications/startup\">Application Settings…</a> ziyarət edin"
Please translate “Application Settings…” inside the <a> link

2018-10-21 12:14 UTC, fitojb commented on po/az.po
> +msgstr "Kısayolları yerləşdirin"
Missing colon at the end of the string:
```suggestion
msgstr "Kısayolları yerləşdirin:"
```

2019-05-06 08:38 UTC, davidmhewitt commented
I'm going to close this pull request as the improvements suggested in the review (thanks @fitojb) have not been made, and I don't have write access to this branch to make them myself.

If someone is still available to improve this translation, please open another pull request.

2019-05-06 08:38 UTC, closed without merging